server:
  port: ${INTERACTION_SERVER_PORT:8500}
spring:
  application:
    name: interaction-service
  config:
    import: "optional:nacos:application.yml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: health,info
