-- transcode-service: 视频流转码调度任务工单表
-- 独占 transcode_* 表所有权，记录各画质规格转码状态、产物文件引用与执行耗时
CREATE TABLE IF NOT EXISTS `transcode_task` (
    `id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '转码任务全局唯一ID (UUID无横杠)',
    `video_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '关联的主视频ID (video_content.id)',
    `author_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创作者账号ID (auth_account.id)',
    `source_file_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '待转码的原始文件ID (file_asset.id)',
    `target_quality` VARCHAR(16) NOT NULL COMMENT '目标清晰度规格: 360P, 480P, 720P, 1080P, 1080P_60, 4K',
    `target_format` VARCHAR(16) NOT NULL DEFAULT 'MP4' COMMENT '流媒体封装格式: MP4, HLS, DASH',
    `target_codec` VARCHAR(16) NOT NULL DEFAULT 'H264' COMMENT '视频压缩编码: H264, H265, AV1',
    `status` VARCHAR(24) NOT NULL DEFAULT 'PENDING' COMMENT '状态流转: PENDING, DOWNLOADING, TRANSCODING, UPLOADING, NOTIFYING, COMPLETED, FAILED',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试执行次数',
    `max_retries` INT NOT NULL DEFAULT 3 COMMENT '最大重试次数上限',
    `output_file_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '转码产物在 file_asset 中注册的文件ID',
    `output_file_size` BIGINT NULL COMMENT '转码产物字节大小',
    `output_bitrate` INT NULL COMMENT '产物实际视频码率 (kbps)',
    `output_fps` INT NULL COMMENT '产物实际视频帧率 (fps)',
    `output_width` INT NULL COMMENT '产物实际像素宽度',
    `output_height` INT NULL COMMENT '产物实际像素高度',
    `video_duration` INT NULL COMMENT '探测得出的视频实际时长 (秒)',
    `error_message` VARCHAR(1000) NULL COMMENT '异常失败详细信息摘要',
    `transcode_cost_ms` BIGINT NULL COMMENT 'FFmpeg 纯转码计算耗时 (毫秒)',
    `total_cost_ms` BIGINT NULL COMMENT '任务全生命周期总耗时 (毫秒)',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_video_quality_format` (`video_id`, `target_quality`, `target_format`),
    KEY `idx_status_created` (`status`, `created_at`),
    KEY `idx_video_id` (`video_id`),
    CONSTRAINT `ck_transcode_quality` CHECK (`target_quality` IN ('360P', '480P', '720P', '1080P', '1080P_60', '4K')),
    CONSTRAINT `ck_transcode_format` CHECK (`target_format` IN ('MP4', 'HLS', 'DASH')),
    CONSTRAINT `ck_transcode_codec` CHECK (`target_codec` IN ('H264', 'H265', 'AV1')),
    CONSTRAINT `ck_transcode_status` CHECK (`status` IN ('PENDING', 'DOWNLOADING', 'TRANSCODING', 'UPLOADING', 'NOTIFYING', 'COMPLETED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频流转码调度任务工单表';
