-- audit-service: 内容安全审核主任务表
CREATE TABLE IF NOT EXISTS `audit_task` (
    `id` CHAR(32) NOT NULL COMMENT '任务主键ID (UUID)',
    `task_no` VARCHAR(64) NOT NULL COMMENT '业务流水号 (如 aud_20260915_xxxx)',
    `biz_type` VARCHAR(32) NOT NULL DEFAULT 'VIDEO' COMMENT '业务类型: VIDEO, COMMENT, AVATAR',
    `biz_id` CHAR(32) NOT NULL COMMENT '业务内部主键 (对应 video_content.id)',
    `biz_vid` VARCHAR(32) NULL COMMENT '业务公开短码 (对应 video_content.vid)',
    `author_id` CHAR(32) NOT NULL COMMENT '作者账号ID',
    `title_snapshot` VARCHAR(128) NOT NULL COMMENT '标题快照',
    `description_snapshot` VARCHAR(2000) NULL COMMENT '简介快照',
    `cover_file_id` CHAR(32) NOT NULL COMMENT '封面图片文件ID',
    `video_file_id` CHAR(32) NOT NULL COMMENT '视频文件ID',
    `stage` VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '审核阶段: RECEIVED, MACHINE_AUDITING, MANUAL_PENDING, FINISHED',
    `result` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '审核结果: PENDING, PASSED, REJECTED',
    `reject_reason` VARCHAR(255) NULL COMMENT '审核驳回原因',
    `review_level` VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '风险级别: NORMAL, SUSPICIOUS, ILLEGAL',
    `operator_id` VARCHAR(64) NOT NULL DEFAULT 'SYSTEM' COMMENT '终审操作人 (SYSTEM 或 管理员ID)',
    `callback_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '回调状态: PENDING, SUCCESS, FAILED',
    `callback_retries` INT NOT NULL DEFAULT 0 COMMENT '回调已重试次数',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_audit_task_no` (`task_no`),
    KEY `idx_audit_biz` (`biz_type`, `biz_id`, `created_at`),
    KEY `idx_audit_stage_result` (`stage`, `result`, `created_at`),
    KEY `idx_audit_callback` (`callback_status`, `updated_at`),
    CONSTRAINT `ck_audit_task_stage` CHECK (`stage` IN ('RECEIVED', 'MACHINE_AUDITING', 'MANUAL_PENDING', 'FINISHED')),
    CONSTRAINT `ck_audit_task_result` CHECK (`result` IN ('PENDING', 'PASSED', 'REJECTED')),
    CONSTRAINT `ck_audit_task_review_level` CHECK (`review_level` IN ('NORMAL', 'SUSPICIOUS', 'ILLEGAL')),
    CONSTRAINT `ck_audit_task_callback_status` CHECK (`callback_status` IN ('PENDING', 'SUCCESS', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容安全审核主任务表';
